server {
  listen 80;
  root /usr/share/nginx/html;
  location /auth/         { proxy_pass http://auth-service:8000; }
  location /appointments  { proxy_pass http://appointment-service:8000; }
  location /records       { proxy_pass http://patient-records-service:8000; }
  location / { try_files $uri /index.html; }
}
