name: notification-service
image:
  repository: 419109630220.dkr.ecr.us-east-1.amazonaws.com/mediconnect/notification-service
  tag: latest
serviceAccount: { roleArn: "arn:aws:iam::419109630220:role/mediconnect-dev-notification" }
env:
  AWS_REGION: us-east-1
  REMINDER_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/419109630220/mediconnect-dev-reminders
  SES_SENDER: no-reply@example.com
