apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: { name: mediconnect, namespace: argocd }
spec:
  sourceRepos: ["https://github.com/KManikanta-DevOps/mediconnect.git"]
  destinations: [{ namespace: mediconnect, server: https://kubernetes.default.svc }]
  clusterResourceWhitelist: []
