name: notification-service
image:
  repository: 573844543866.dkr.ecr.us-east-1.amazonaws.com/mediconnect/notification-service
  tag: a01fac6
serviceAccount: { roleArn: "arn:aws:iam::573844543866:role/mediconnect-dev-notification" }
env:
  AWS_REGION: us-east-1
  REMINDER_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/573844543866/mediconnect-dev-reminders
  SES_SENDER: no-reply@example.com
