name: patient-records-service
image:
  repository: 573844543866.dkr.ecr.us-east-1.amazonaws.com/mediconnect/patient-records-service
  tag: a01fac6
serviceAccount: { roleArn: "arn:aws:iam::573844543866:role/mediconnect-dev-patient-records" }
env:
  AWS_REGION: us-east-1
  COGNITO_USER_POOL_ID: us-east-1_qFRwJvM2Q
  COGNITO_CLIENT_ID: 2kranvtq6ciq8lf0l9nq8o3he5
  REPORTS_BUCKET: mediconnect-dev-reports-573844543866
  KMS_KEY_ID: alias/mediconnect-dev
secretEnv:
  DATABASE_URL: { secretName: records-db, key: url }
ingress: { enabled: false, host: dev.mediconnect.example.com, path: /records, certificateArn: "arn:aws:acm:..." }
