name: terraform
on:
  pull_request: { paths: ["infra/terraform/**"] }
  workflow_dispatch:
    inputs:
      env: { description: "dev | stage | prod", default: dev }
      apply: { description: "apply? (true/false)", default: "false" }

permissions: { id-token: write, contents: read, pull-requests: write }

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: infra/terraform } }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform workspace select -or-create ${{ inputs.env || 'dev' }}
      - run: terraform validate
      - run: terraform plan -var-file=envs/${{ inputs.env || 'dev' }}.tfvars -out=tfplan
      - if: inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan
